info:
  contact: {}
paths:
  /api/v1/sys/dept:
    post:
      description: 这是一段接口描述
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增部门
      tags:
      - 部门管理
  /api/v1/sys/dept/:id:
    delete:
      description: 这是一段接口描述
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除部门
      tags:
      - 部门管理
    put:
      description: 这是一段接口描述
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 更新部门
      tags:
      - 部门管理
  /api/v1/sys/role:
    get:
      description: 这是一段接口描述
      parameters:
      - description: 角色编码
        in: query
        name: code
        type: string
      - description: 角色名称
        in: query
        name: name
        type: string
      - description: 角色状态
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取角色列表
      tags:
      - 角色管理
    post:
      description: 这是一段接口描述
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增角色
      tags:
      - 角色管理
  /api/v1/sys/role/:id:
    delete:
      description: 这是一段接口描述
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除角色
      tags:
      - 角色管理
    put:
      description: 这是一段接口描述
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 更新角色
      tags:
      - 角色管理
  /api/v1/sys/roles:
    get:
      description: 这是一段接口描述
      produces:
      - application/json
      responses: {}
      summary: 获取部门
      tags:
      - 部门管理
swagger: "2.0"
